plugins {
    id 'fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'
}

version = project.platform+"-"+project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_name
}

loom {
    //splitEnvironmentSourceSets()
}

repositories {
    maven {
        url = "https://cursemaven.com"
        allowInsecureProtocol = true
    }
    maven {
        name = "REI"
        url = "https://maven.shedaniel.me/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
            includeGroup "dev.architectury"
        }
    }
    maven {
        name = "Greenhouse Maven"
        url = 'https://maven.greenhouse.lgbt/releases/'
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    compileOnly "com.google.auto.service:auto-service:1.1.0"
    annotationProcessor "com.google.auto.service:auto-service:1.1.0"
    modImplementation "net.fabricmc:fabric-loader:$project.fabric_loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$project.fabric_api_version"
    modRuntimeOnly "curse.maven:modmenu-308702:5810603"
    modImplementation("vectorwing:FarmersDelight:${fdrf_version}") {
        exclude(group: "net.fabricmc")
    }
    // compile against the JEI API but do not include it at runtime
    modCompileOnly("mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}")
    // at runtime, use the full JEI jar for Fabric
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-fabric:${jei_version}")
    modRuntimeOnly("curse.maven:jade-324717:6738760")
    modRuntimeOnly("curse.maven:just-enough-effect-descriptions-jeed-532286:7346554")
    modRuntimeOnly("curse.maven:food-effect-tooltips-695850:6024177")
    modRuntimeOnly("curse.maven:cloth-config-348521:5729125")
    modRuntimeOnly("curse.maven:appleskin-248787:5864741")
    modRuntimeOnly("curse.maven:advanced-loot-info-1205426:8002072")
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    modImplementation("curse.maven:eternal-starlight-1080592:8102436")

}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.fabric_loader_version
    inputs.property "mod_id", project.mod_id
    inputs.property "mod_description", project.mod_description
    inputs.property "mod_name", project.mod_name
    inputs.property "mod_license", project.mod_license
    inputs.property "mod_authors", project.mod_authors
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.fabric_loader_version,
                "mod_id": project.mod_id,
                "mod_description": project.mod_description,
                "mod_name": project.mod_name,
                "mod_license": project.mod_license,
                "mod_authors": project.mod_authors
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
fabricApi {
    configureDataGeneration()
}