# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
# Mod properties
mod_version=1.3.0
mod_id=eternal_starlight_delight
mod_name=Eternal Starlight's Delight
maven_group=com.minor2CCh
archives_name=eternal-starlight-delight
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version_range=[21,)
loader_version_range=[4,)
mod_license=MIT
mod_authors=Minor2CCh
mod_description=An unofficial mod that adds collaborative elements between Farmer's Delight and Eternal Starlight.
# Dependencies
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
neoforge_version=21.1.228
jei_version=19.27.0.340
rei_version=16.0.799
fdrf_version=1.21.1-3.3.3+refabricated
platform=fabric
# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
